import * as THREE from 'three';
import { Client, handle_file } from '@gradio/client';
import { unzipSync } from 'fflate';

const audio = document.querySelector('#audio');
const audioInput = document.querySelector('#audioFile');
const btn = document.querySelector('#generateCamn');
const grid = document.querySelector('#grid');
const statusEl = document.querySelector('#backendStatus');

const JOINTS={hips:null,spine:'hips',chest:'spine',neck:'chest',head:'neck',leftShoulder:'chest',leftUpperArm:'leftShoulder',leftForeArm:'leftUpperArm',leftHand:'leftForeArm',rightShoulder:'chest',rightUpperArm:'rightShoulder',rightForeArm:'rightUpperArm',rightHand:'rightForeArm',leftUpperLeg:'hips',leftLowerLeg:'leftUpperLeg',leftFoot:'leftLowerLeg',rightUpperLeg:'hips',rightLowerLeg:'rightUpperLeg',rightFoot:'rightLowerLeg'};
const REST={hips:[0,1.02,0],spine:[0,.20,0],chest:[0,.30,0],neck:[0,.25,0],head:[0,.20,0],leftShoulder:[-.18,.05,0],leftUpperArm:[-.18,0,0],leftForeArm:[-.31,0,0],leftHand:[-.27,0,0],rightShoulder:[.18,.05,0],rightUpperArm:[.18,0,0],rightForeArm:[.31,0,0],rightHand:[.27,0,0],leftUpperLeg:[-.11,-.08,0],leftLowerLeg:[0,-.45,0],leftFoot:[0,-.43,.08],rightUpperLeg:[.11,-.08,0],rightLowerLeg:[0,-.45,0],rightFoot:[0,-.43,.08]};
const SMPLX={hips:0,leftUpperLeg:1,rightUpperLeg:2,spine:3,leftLowerLeg:4,rightLowerLeg:5,chest:9,leftFoot:10,rightFoot:11,neck:12,leftShoulder:13,rightShoulder:14,head:15,leftUpperArm:16,rightUpperArm:17,leftForeArm:18,rightForeArm:19,leftHand:20,rightHand:21};
let motion=null,view=null,card=null,generating=false;
const setStatus=s=>{if(statusEl)statusEl.textContent=s;};
const urlOf=v=>typeof v==='string'?v:(v?.url||v?.path||v?.orig_name||v?.name||null);

function parseNpy(bytes){const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(dv.getUint8(0)!==0x93)throw new Error('NPY inválido');const major=dv.getUint8(6);let n,o;if(major===1){n=dv.getUint16(8,true);o=10}else{n=dv.getUint32(8,true);o=12}const h=new TextDecoder().decode(bytes.subarray(o,o+n));o+=n;const d=h.match(/'descr':\s*'([^']+)'/)?.[1],shape=(h.match(/'shape':\s*\(([^)]*)\)/)?.[1]||'').split(',').map(x=>x.trim()).filter(Boolean).map(Number);if(!d||!shape.length)throw new Error('NPY no soportado');const count=shape.reduce((a,b)=>a*b,1),out=new Float64Array(count),little=d[0]!=='>';if(d.endsWith('f4'))for(let i=0;i<count;i++)out[i]=dv.getFloat32(o+i*4,little);else if(d.endsWith('f8'))for(let i=0;i<count;i++)out[i]=dv.getFloat64(o+i*8,little);else throw new Error(`dtype ${d} no soportado`);return{shape,data:out};}
function quat(x,y,z){const a=Math.hypot(x,y,z);if(a<1e-8)return[0,0,0,1];const s=Math.sin(a/2)/a;return[x*s,y*s,z*s,Math.cos(a/2)];}
function slerp(a,b,t){let dot=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3],bb=b;if(dot<0){dot=-dot;bb=b.map(x=>-x)}if(dot>.9995){const q=a.map((x,i)=>x+(bb[i]-x)*t),n=Math.hypot(...q);return q.map(x=>x/n)}const th=Math.acos(Math.max(-1,Math.min(1,dot))),sn=Math.sin(th);return a.map((x,i)=>(Math.sin((1-t)*th)/sn)*x+(Math.sin(t*th)/sn)*bb[i]);}
function npzToMotion(buffer){const zip=unzipSync(new Uint8Array(buffer)),keys=Object.keys(zip),key=keys.find(k=>/(^|\/)poses\.npy$/i.test(k));if(!key)throw new Error('NPZ sin poses.npy');const arr=parseNpy(zip[key]),T=arr.shape[0],D=arr.shape.at(-1);if(D<66)throw new Error(`poses inválido (${D} valores/frame)`);const frames=[];for(let f=0;f<T;f++){const joints={};for(const[name,idx]of Object.entries(SMPLX)){if(name==='hips'){joints[name]={rotation:[0,0,0,1]};continue}const p=f*D+idx*3;joints[name]={rotation:quat(arr.data[p],arr.data[p+1],arr.data[p+2])}}frames.push({root:{position:[0,0,0]},joints})}return{model:'camn',generator:'CaMN official EMAGE Space',fps:30,frames};}
async function decode(file){const c=new AudioContext();try{return await c.decodeAudioData(await file.arrayBuffer())}finally{c.close()}}
function wav(buf,s,e,name){const sr=buf.sampleRate,a=Math.floor(s*sr),b=Math.min(buf.length,Math.floor(e*sr)),len=b-a,ch=buf.numberOfChannels,ab=new ArrayBuffer(44+len*ch*2),dv=new DataView(ab);let o=0;const ws=x=>{for(const c of x)dv.setUint8(o++,c.charCodeAt(0))},u32=x=>{dv.setUint32(o,x,true);o+=4},u16=x=>{dv.setUint16(o,x,true);o+=2};ws('RIFF');u32(36+len*ch*2);ws('WAVE');ws('fmt ');u32(16);u16(1);u16(ch);u32(sr);u32(sr*ch*2);u16(ch*2);u16(16);ws('data');u32(len*ch*2);const data=Array.from({length:ch},(_,i)=>buf.getChannelData(i));for(let i=0;i<len;i++)for(let j=0;j<ch;j++){const x=Math.max(-1,Math.min(1,data[j][a+i]));dv.setInt16(o,x<0?x*32768:x*32767,true);o+=2}return new File([ab],name,{type:'audio/wav'});}
function segments(d){const out=[];let s=0;while(s<d-.01){const e=Math.min(d,s+58);out.push([s,e]);if(e>=d)break;s=e-2}return out;}
function merge(parts){let out={...parts[0],frames:[...parts[0].frames]};const n0=60;for(let c=1;c<parts.length;c++){const b=parts[c],n=Math.min(n0,out.frames.length,b.frames.length);for(let i=0;i<n;i++){const A=out.frames[out.frames.length-n+i],B=b.frames[i],t=(i+1)/(n+1);for(const j of Object.keys(SMPLX)){const qa=A.joints?.[j]?.rotation,qb=B.joints?.[j]?.rotation;if(qa&&qb)A.joints[j].rotation=slerp(qa,qb,t)}}out.frames.push(...b.frames.slice(n))}return out;}
async function getNpz(result){const arr=result?.data||[],v=arr.find(x=>/\.npz(?:$|\?)/i.test(urlOf(x)||''))||arr[4],u=urlOf(v);if(!u)throw new Error('CaMN respondió pero no encontré el NPZ');const r=await fetch(u);if(!r.ok)throw new Error(`No pude descargar NPZ (${r.status})`);return r.arrayBuffer();}

function makeViewer(container){const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.01,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));container.appendChild(renderer.domElement);const root=new THREE.Group();scene.add(root);const joints={},bones=[],jm=new THREE.MeshBasicMaterial({color:0xd8e1ff}),bm=new THREE.MeshBasicMaterial({color:0x8ca2ff}),rm=new THREE.MeshBasicMaterial({color:0xffc76b});for(const[n,p]of Object.entries(JOINTS)){const g=new THREE.Group();g.position.fromArray(REST[n]);g.add(new THREE.Mesh(new THREE.SphereGeometry(n==='head'?.07:(n==='hips'?.035:.024),14,10),n==='hips'?rm:jm));joints[n]=g;if(p)joints[p].add(g);else root.add(g)}root.updateMatrixWorld(true);for(const[n,p]of Object.entries(JOINTS)){if(!p)continue;const m=new THREE.Mesh(new THREE.CylinderGeometry(.013,.013,1,8),bm);scene.add(m);bones.push({m,a:joints[p],b:joints[n]})}camera.position.set(0,1.2,4);camera.lookAt(0,1.1,0);function resize(){const r=container.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(container);resize();return{scene,camera,renderer,root,joints,bones};}
function reset(){for(const[n,o]of Object.entries(view.joints)){o.position.fromArray(REST[n]);o.quaternion.identity()}view.root.position.set(0,0,0);view.root.quaternion.identity();}
function pose(t){reset();if(!motion?.frames?.length){view.joints.leftUpperArm.rotation.z=.05;view.joints.rightUpperArm.rotation.z=-.05;return}const f=Math.max(0,Math.min(motion.frames.length-1,t*30)),a=Math.floor(f),b=Math.min(motion.frames.length-1,a+1),x=f-a;for(const n of Object.keys(JOINTS)){const A=motion.frames[a]?.joints?.[n]?.rotation,B=motion.frames[b]?.joints?.[n]?.rotation||A;if(A&&B)view.joints[n].quaternion.copy(new THREE.Quaternion(...A)).slerp(new THREE.Quaternion(...B),x)}}
function draw(){if(!view)return;pose(audio?.currentTime||0);view.root.updateMatrixWorld(true);const av=new THREE.Vector3(),bv=new THREE.Vector3(),mid=new THREE.Vector3(),up=new THREE.Vector3(0,1,0);for(const b of view.bones){b.a.getWorldPosition(av);b.b.getWorldPosition(bv);const d=bv.clone().sub(av),len=d.length();if(len<1e-6)continue;mid.copy(av).add(bv).multiplyScalar(.5);b.m.position.copy(mid);b.m.scale.set(1,len,1);b.m.quaternion.setFromUnitVectors(up,d.normalize())}const mode=document.querySelector('.view-button.active')?.dataset.view||'front';if(mode==='front')view.camera.position.set(0,1.18,4);if(mode==='side')view.camera.position.set(4,1.18,0);if(mode==='threequarter')view.camera.position.set(2.7,1.35,2.7);view.camera.lookAt(0,1.1,0);view.renderer.render(view.scene,view.camera);requestAnimationFrame(draw);}

async function run(){const file=audioInput.files?.[0];if(!file||generating)return;generating=true;btn.disabled=true;const badge=card.querySelector('.status');badge.textContent='Generando…';badge.classList.remove('real');try{const dec=await decode(file),segs=segments(dec.duration),app=await Client.connect('H-Liu1997/EMAGE'),parts=[];for(let i=0;i<segs.length;i++){const[s,e]=segs[i];setStatus(`CaMN: tramo ${i+1}/${segs.length} (${s.toFixed(0)}–${e.toFixed(0)} s) · esperando ZeroGPU…`);const result=await app.predict('/inference_app',{audio:handle_file(wav(dec,s,e,`camn_${i}.wav`)),model_type:'CaMN (Upper only)',render_mesh:false,render_face:false,render_mesh_face:false});parts.push(npzToMotion(await getNpz(result)))}motion=merge(parts);badge.textContent='Movimiento real · CaMN';badge.classList.add('real');card.querySelector('.download').disabled=false;setStatus(`CaMN: LISTO · ${(motion.frames.length/30).toFixed(1)} s · ${segs.length} tramo(s).`)}catch(e){console.error(e);badge.textContent='Error backend';setStatus(`CaMN: error — ${e.message||e}`)}finally{generating=false;btn.disabled=!audioInput.files?.[0]}}

card=document.createElement('article');card.className='viewer-card';card.dataset.model='camn';card.innerHTML=`<div class="viewer-head"><div><div class="viewer-title">CaMN</div><div class="viewer-meta">Upper-body · REAL BACKEND</div></div><span class="status">Sin resultado real</span></div><div class="canvas-wrap"></div><div class="viewer-foot"><span class="metric">30 FPS</span><span class="metric">Audio-driven</span><span class="metric">Upper body</span><span class="spacer"></span><button class="download" disabled>Descargar JSON</button></div>`;grid?.appendChild(card);view=makeViewer(card.querySelector('.canvas-wrap'));card.querySelector('.download').addEventListener('click',()=>{if(!motion)return;const a=document.createElement('a'),blob=new Blob([JSON.stringify(motion,null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download='camn-motion.json';a.click();URL.revokeObjectURL(a.href)});btn?.addEventListener('click',run);audioInput?.addEventListener('change',()=>{if(btn)btn.disabled=!audioInput.files?.[0]});draw();